Repository JuliaGeometry/Quaternions.jl, pull requests merged in 2022-02, with the labels that each got.

#53 fix piracy and type instability
  src/Quaternion.jl
  test/test_Quaternion.jl
Labels: bug

#49 Add support for exp(::Quaternion{Int})
  src/Quaternion.jl
  test/test_Quaternion.jl
Labels: bug

#63 Add convenient type-aliases
  Project.toml
  src/DualQuaternion.jl
  src/Octonion.jl
  src/Quaternion.jl
  src/Quaternions.jl
  test/test_Quaternion.jl
Labels: enhancement

#52 improve promotion and equality checking
  src/DualQuaternion.jl
  src/Octonion.jl
  src/Quaternion.jl
  src/Quaternions.jl
  test/test_Quaternion.jl
Labels: bug, enhancement

#68 Add documentation with Documenter.jl
  .github/workflows/ci.yml
  .gitignore
  README.md
  docs/Project.toml
  docs/make.jl
  docs/src/index.md
Labels: documentation

#56 Extend all analytic functions in base for quaternions
  Project.toml
  README.md
  src/Quaternion.jl
  test/test_Quaternion.jl
Labels: enhancement
